spring:
  datasource:
    url: jdbc:h2:mem:portfolio
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}

spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enabled: false

management:
  health:
    mail:
      enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://saikrishnagottapu.vercel.app}
